// Code generated by boil, DO NOT EDIT

package {{.Vars.PackageName}}

import (
	"database/sql"
	_ "github.com/go-sql-driver/mysql"
)

func Create(in {{declaration .Vars.TypeName | .Name}}) error {
	return nil
}